/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew cask install 1password
brew cask install android-file-transfer
brew cask install appcleaner
brew cask install atom
brew cask install google-backup-and-sync
brew cask install clipy
brew cask install dropbox
brew cask install firefox
brew cask install gimp
brew cask install google-chrome
brew cask install keka
brew cask install linein
brew cask install little-snitch
brew cask install avibrazil-rdm
brew cask install transmission
brew cask install tunnelblick
brew cask install vlc
brew cask install veracrypt
brew cask install whatsapp
brew cask install coconutbattery
brew cask install iterm2
brew cask install flash-npapi
brew cask install xscreensaver
